label scene_12:
    play env "amb/workshop.ogg" fadein 2.0
    na "Well, it took a few days, but I think I have everything working now."
    na "The drive's in place, albeit with a few… extra modifications to work with my custom chassis."
    na "The rest of the parts Leona and I found were more than enough to get the rest of the ship up and running."
    mc "I think… we're ready."

    #show leona

    le "Ready for what?"
    mc "Ah, hey there."
    le "Hey."
    na "Just hearing her voice is uplifting."
    na "She's done so much for me. Not just for the ship, but… something more."
    mc "I was thinking… remember last night?"
    le "About the test flight?"
    mc "Yeah. I think we have things ready to go for one today. Interested?"
    le "Do you have to ask? Of course I am!"
    mc "Well, step aboard!"

    #show BG_new_ship

    na "The ship's interior is mostly how I remember it, but we had to make room for some of the older drive tech."
    na "Kind of reminds me of the old holovids I used to watch as a kid."
    na "Humans apparently thought you could get to the moon in just a tiny, cramped capsule launched out of a cannon."
    na "Now, several centuries later, it looks like I'm doing much of the same."
    na "Minus the cannon part, that is."
    ju "Oh hey, Raine. You ready for a test flight today?"
    ju "I can take the new girl up too. This 'new' drive you installed is pretty old, but it's twice as powerful as the one you made yourself."
    mc "Hey!"
    ju "Just stating the facts."
    na "I'm… a little insulted, but also surprised that the drive really is that powerful."
    mc "How's everything else looking, Juneau?"
    ju "Your hodgepodge assemblage of parts is looking good!"
    mc "Really? That's what you called the ship the {b}first{/b} time I tested it on Lumin."
    ju "No, I mean it this time. Despite the crash, you've done a good job getting this thing back into shape."
    ju "Good job!"
    mc "Heh, thanks. But it wasn't just me."
    na "Leona finally stops moving around the cabin in time for me to indirectly mention her."
    le "Oh, I helped!"
    na "Leona here found the parts we needed to get back in business."
    ju "So I've heard. Good morning, Leona."
    le "Hi!"
    le "So, anything else we need to do?"
    ju "Nope, you can just take a seat and strap in."
    le "Woo-hoo!"
    na "Leona eagerly sits down at the nearest chair and bounces happily, waiting for me to sit down as well."
    mc "Okay, okay, easy girl."
    na "I take a seat and get the ship ready for launch."
    stop env fadeout 1.0

    #plane engine SFX
    play sound "sfx/engines up.ogg"
    pause 2.0
    play env "sfx/engines3.ogg" fadein 1.0

    le "So how do we get to — "
    play sound3 "sfx/engines2.ogg" fadein 1.0

    #faster engine SFX

    le " — spaaaaaaaaaaaaaaaaaaace!?!"

    na "The new drive whirs to life and rapidly accelerates us to escape velocity."
    play sound "sfx/power down 2.ogg"
    stop env fadeout 1.0
    stop sound3 fadeout 1.0
    na "In about a minute, we're at the edge of the atmosphere, successfully in orbit around Fireside."

    ju "Okay, we're stable. You guys want to try zero gravity?"
    play music "music/floating.ogg" fadein 2.0
    le "Huh?"
    mc "C'mon, let me show you!"
    na "In one smooth motion, I unbuckle myself and Leona from our seats, and we start floating out of our chairs."
    le "Ah! I'm floating!"
    mc "That's what zero gravity does, silly."
    na "I guide her around the cabin, showing her how to move around."
    le "Wheeee!"
    mc "Hey, now you're getting it!"
    na "Her eagerness is infectious. I don't know why, but when I see her grinning like that, I'm doing the exact same thing."
    na "Why haven't I been doing that?"
    na "How long has it been since I've really enjoyed myself?"
    na "Leona's been a bright, shining light in the darkness of my life."
    na "I can't help but be drawn to her."

    stop music fadeout 2.0


    #timeskip
    play env "amb/Leonas house.ogg" fadein 2.0
    na "Sometime later, we finish up our test flight and land back on Fireside."
    le "Raine, that was amazing!"
    mc "Was that your first time flying?"
    le "Not like that. My hoverbike is the most I've ever been off the ground."
    mc "You're missing out."
    le "On Dawne, they have bigger aircraft that can take lots of people and cargo, but we don't have anything like that on Fireside."
    mc "Why?"
    le "We don't have a need for it at the moment. We've spent most of our time and resources focused on building out Aster."
    mc "Ah, makes sense."
    na "Living here on this planet is like traveling through time. All the primitive tech, the lack of familiar amenities, and the open space here is nothing like I anticipated."
    na "It's equal parts exhilarating and exhausting."
    na "I'm so far from home, and yet I'm so excited to be here."
    na "I want to head out into space, but I can't help but wonder…"
    na "Would I be happier staying here with Leona?"
    le "Raine?"
    mc "Hm?"
    le "You looked like you were spacing out again. You okay?"
    mc "Yeah, sorry. Just a bit tired."
    le "Well, it's getting late anyway. Let's head home! I'll cook for you."
    mc "I'd like that."
    na "With the ship repaired, it's a simple matter to land within a few minutes of Leona's house."
    na "Leona points at the controls, asking about all of their functions while I fly us home."
    na "She's seriously cute when she does that."
    mc "Okay, we're here!"
    le "All right! Great flying, Raine! I'll get dinner started!"
    na "Leona wastes no time in jumping out of the ship and setting up dinner."
    na "As she cooks, I can't help but think about our conversation the other night."
    na "Would Leona really be okay with me taking her with me?"
    na "She's got so much here: her people, her culture, and I'm sure she's got a lot of close friends and family she'd miss, too."
    na "And yet…"
    na "It'd be so easy to say 'yes' and take her with me."
    na "She'd be overjoyed. But is she doing this because she's in love with — "
    na "Oh my God."
    le "Raine? You there?"
    na "That's why she wants to come with."
    na "I'm such an idiot."
    mc "Ah, sorry. Geez, I'm more tired than I thought."
    le "Maybe some food will help! Come on, eat with me."
    mc "Can't say no to that. Thanks, Leona!"
    na "The food is delicious. Leona's got an amazing sense for cooking."
    na "We enjoy a wonderful night in, staying close and enjoying each other's company."
    le "Hey, Raine…"
    mc "Yeah?"
    le "Tell me about Lumin."
    mc "Why?"
    le "I just want to know what your home is like."
    mc "Well, it's mostly urban. The whole planet is one big city, save for a few places."
    mc "The entire city is this one big hub of information, electricity, and people."
    mc "For a while, it was home."
    mc "I managed to make a living as an engineer and for a while, it was fun."
    le "For a while?"
    mc "Yeah."
    mc "Something in me just got… sad, I guess. I wanted to see what was out there."
    mc "I kept thinking to myself, 'Is this it for me? Could I be doing more with my life?'"
    mc "So I decided I'd get out there and explore. I built a ship and took off."
    le "And that's how you ended up here?"
    mc "That's right."
    le "I think I understand. You really wanted to explore, like me."
    mc "Yeah."
    le "That's so cool! I don't know if I would have been able to do all of that on my own."
    le "You're really brave."
    mc "Heh, thanks."
    mc "It was pretty scary, actually."
    mc "I just… up and left without much fanfare. Heck, my flat is still there with a few of my things."
    mc "It was kind of impulsive."
    le "I'll say!"
    mc "But, you know..."
    na "I reach out and hold her hand."
    mc "I'd do it all over again if it meant I could meet you every time."
    le "Raine, I… wow."
    na "Her cheeks are so red they're practically glowing."
    le "That's um…"
    le "Um…"
    le "..."
    stop env fadeout 2.0
    #show kiss_CG1
    #pause (3)
    na "The kiss lingers in the air, fading out all of the sounds of the city outside."
    na "The two of us say nothing for a while as Leona holds me close to her."
    #pause (3)
    le "Raine… I love you."
    le "I want to go with you! I want to travel and see all the other stars in the sky!"
    le "I just… don't want you to go, Raine!"
    le "I don't want to be alone…"
    #show kiss_CG2
    play music "music/they cry.ogg" fadein 2.0
    play sound3 "amb/leonas house.ogg" fadein 2.0
    na "Her voice breaks as she starts crying."
    na "I'm stunned. All I can do is hug her tighter in response."
    na "There's so much I want to say."
    na "But I can't say them."
    na "Leona's been there for me, ever since I fell out of the sky."
    na "She's given me a home, showed me the beautiful planet, and even given me a reason to stay in one place for longer than a few days."
    na "But I still feel that yearning for more adventure."
    na "I know that I can't stay here."
    na "I know that I'll always want to travel amongst the stars."
    na "But still…"
    na "But still…!"
    mc "Leona…"
    #show kiss_CG3
    na "I love you too."
    na "My body is screaming at me to say it."
    na "But I can't do it."
    mc "Forgive me… but I have to leave Fireside."
    mc "The wormhole is going to close in a few days, if not hours."
    mc "I have to go now, or I'll never make it home."
    le "But you… can't take me with you?"
    mc "I… don't know."
    #end CG
    mc "You see… that wormhole I traveled through… it's a one-way trip."
    mc "If I — or both — of us go through there, we might not come back here for a while."
    mc "We might not come back here ever again."
    mc "Do you think you can really leave your people here, just like that?"
    le "Didn't you?"
    mc "..."
    mc "I…"
    le "You don't think I can make those kinds of sacrifices, too? That I should just stay here and forget all about you?"
    le "No. I can't ever forget about you, Raine!"
    le "If you think you have to do this all by yourself, that's fine."
    le "But it's not fair to me… what you're doing to my heart…"
    na "Leona quickly starts crying, and I can't hold back my tears as well."
    na "I run outside towards the ship."
    #show outdoors_night
    stop sound3 fadeout 2.0
    play env "amb/city night.ogg" fadein 2.0
    na "The night air is cool and crisp, almost like a slap to the face."
    na "I have to do this now, or I'll miss my chance."
    na "If I leave the way I am now, I can do it with no regrets."
    na "Finally, the ship comes into view."
    na "This is it. It's time to leave Fireside behind for good."
    mc "Open up, Juneau!"
    mc "We're heading out."
    na "The ship's bay doors open, and I hop inside."
    ju "It's so late, though… can't it wait until morning?"
    #show inside_ship
    mc "No, we should leave early before the wormhole closes."
    ju "And your girlfriend? Is she coming, too?"
    mc "W-what?"
    ju "I saw the way you looked at her earlier. You're in love with her, right?"
    mc "What makes you say that?"
    ju "The Raine I know doesn't smile like that at just anyone."
    ju "Not even me."
    ju "And frankly, I'm insulted."
    mc "About… what, exactly?"
    ju "That you fall head over heels for an alien, yet you still insist on putting your boots up on my console every time, despite all we've been through."
    ju "Honestly, you humans are so weird about love. It's like you're hard-wired to do the stupidest stuff when your hormones go off."
    mc "I'm not… stupid."
    ju "But you {b}are{/b} in love, no?"
    #pause (5)
    mc "...You're right."
    na "Juneau's odd pep talk seems to have worked."
    mc "I love her."
    mc "I love Leona!"
    na "And I need to tell her."
    mc "Juneau… thank you."
    ju "Anything for a friend. Now get going!"
    mc "Right!"
    stop env fadeout 2.0
    play sound3 "amb/leonas house.ogg" fadein 2.0
    #show leona_house
    na "I run back to a still-sobbing Leona, who's curled up in her piles of cushions in a vain attempt to sleep."
    na "She instantly embraces me."
    le "Raine… Raine!"
    mc "Hey, it's okay. I'm here now."
    mc "I'm sorry. I was being selfish."
    mc "I was so focused on getting home I didn't stop to think what would happen if I…"
    mc "If I fell in love with you."
    le "Raine…"
    mc "But now I know what I should do."
    mc "I'm taking you with me, Leona, because we need each other in this beautiful universe."
    le "Hehe… okay!"
    le "Yeah… I'll go with you. Wherever you want to go."
    le "And that's because I know that no matter what, we'll have fun."
    mc "Yeah. You're absolutely right."
    #show kiss_CG4
    na "We kiss again, but this time it's different."
    na "We're not pulling away from each other, we're getting closer and closer."
    na "I'm falling into Leona's gravity well, and all the heat and pressure that comes with it feels so relieving."
    na "And I know she's feeling the same way."
    stop music fadeout 2.0
    mc "I love you, Leona."
    le "I love you too."
    na "We stay in each other's arms for a long, long time after that, until we both fall asleep."

    #timeskip

    na "The next day, I help Leona pack her belongings and get the ship ready for travel."
    na "The hardware I installed makes things a bit cramped, but I think it'll work out."
    na "The first thing we're doing is upgrading this ship to be more roomy, for sure."
    ju "You sure have a lot of stuff, Leona."
    le "Can't leave home without all of these!"
    na "She motions to her bedding, her outfits, and a variety of other knick knacks she's collected."
    ju "I sure hope we can get into orbit with all of this."
    mc "It's fine. The new engine is definitely powerful enough for that."
    mc "Besides… think of the upgrades we can make to this baby once we hit Danhamye or any of the other colonies."
    mc "The I.S.O.C chips are old, but collectors will salivate for anything that ancient."
    mc "Something about 'vintage firmware' that they can use will sell well on pretty much any market."
    ju "I demand a new console, for starters."
    mc "Deal."
    na "The ship looks more and more like Leona's house than it does mine."
    na "Pretty much all of my belongings were destroyed during re-entry, so all I have left is the stuff currently on my person."
    na "Still, Leona's house had its comforts, and we thankfully were able to fit the things that mattered, plus a few extras."
    na "She's dying to show me more of her cooking sometime, so she's brought some of her cookware."
    na "I didn't have the heart to tell her that there's no stove on board, just the synthesizer."
    na "It wouldn't be that hard to install one later, though."
    play music "music/leaving fireside.ogg" fadein 2.0
    mc "Well, I think that's everything."
    le "Got anything else you want to grab before we say goodbye?"
    mc "You packed extra o'eke'ke, right?"
    le "Yup!"
    mc "Then we're fine."
    le "Yay!"
    mc "Are {b}you{/b} ready, Leona? It's going to be a long time before we see Fireside again."
    le "I wouldn't have packed all of my life into your ship if I wasn't ready, Raine."
    na "She sits down and straps herself in."
    le "Let's go!"
    mc "All right then!"
    mc "Juneau, you know what to do!"
    ju "Roger that. Starting up the engines."
    #engine startup
    na "I turn to Leona as I take the ship up."
    na "She gives me her trademark grin as she observes the scenery outside."
    na "Fireside quietly falls away as we reach orbit, the exosphere, and finally, open space."
    le "Wow… there's so many stars!"
    le "So, what's the first stop, Raine?"
    mc "I think we're ready for that wormhole."
    le "What?!? You really want to go through there again?"
    mc "I'm ready this time. I know where it is, and where it'll spit us out."
    mc "Juneau, you have the coordinates, right?"
    ju "Right here."
    na "The wormhole's location pops up on a nearby monitor. Not too far away."
    ju "It's definitely going to close soon. Probably within the next 24 hours."
    ju "Either you go now, or you wait until it {b}might{/b} open up again."
    ju "Which could be anywhere from a month to, well, never."
    ju "You sure you want to go?"
    na "I look to Leona."
    na "She nods, determined."
    mc "We're sure. Let's go!"
    ju "All right, then. Setting engines to maximum!"
    #engine SFX
    mc "The engines accelerate us closer and closer to the wormhole's event horizon."
    ju "600 kilometers until breach."
    mc "Well, here we go, Leona."
    mc "It'll be quite a trip, don't you think? There's a lot out here."
    le "Yeah. But I'm excited to see it all with you."
    na "She leans in for a kiss."
    mc "Thanks, Leona. For everything."
    ju "300 kilometers."
    mc "You're really something out of this world, you know?"
    le "I'd say the same to you, Raine."
    na "We laugh as the ship gets closer and closer to our destination."
    ju "Fifty kilometers."
    na "This is it. I'm finally starting on my great adventure…"
    na "No."
    na "That adventure ended when I met Leona."
    ju "Ten."
    na "When I fell in love with her."
    ju "Five."
    na "And now…"
    #wormhole SFX
    ju "Entering event horizon. We're in the wormhole!"
    le "Woo hoo!"
    na "I'm starting another great adventure with Leona, one that's going to be ten times the adventure the last one was."
    na "One that I can enjoy with her to the fullest."
    mc "Hang on, this one's gonna be bumpy!"
    #wormhole intensifies
    ju "We're going… a lot faster than the speed of light. This wormhole is incredible!"
    ju "Imagine if we could master riding these with bigger ships… there'd be no galaxy beyond our reach!"
    mc "Always happy to pioneer new techniques of transportation!"
    na "The intensity of the wormhole momentarily spikes."
    ju "Gravity is getting stronger here! Watch out!"
    mc "Got it!"
    #switch SFX
    na "I make some on-the-fly adjustments to my flying as the ship careens into oblivion."
    na "Leona's fascinated by it all, enraptured by the lights and colors around her."
    na "God, she's cute."
    na "Soon, the gravity settles down, and Juneau senses that we're near the end."
    ju "Getting ready to decelerate. Don't want to collide with {b}another{/b} asteroid as soon as we leave."
    mc "Good call."
    mc "Almost there! And...."
    na "The ship finally exits the wormhole."
    mc "We're out!"
    ju "Got it! Decelerating."
    na "The ship slows down until we get to a more reasonable speed."
    ju "Exit confirmed. We're about a lightyear from the nearest planet, according to our maps."
    na "Now back in familiar territory, I finally sigh in relief."
    mc "Well Leona, we're here!"
    le "That was awesome! Where should we go first?"
    mc "I think we should try this place out."
    mc "I scroll my map to one place I've been thinking about for a while."
    le "What's that planet?"
    mc "Lumin."
    mc "Home."
    mc "You've shown me your home, so how about I show you mine?"
    le "I'd love that."
    mc "Juneau, take us home!"
    ju "Sounds good to me."
    mc "Whew! That was intense."
    le "It sure was!"
    le "But I'm glad you got us here safe and sound."
    mc "Yeah, me too!"
    le "Well, I'm ready to see your home planet."
    le "Maybe after we stay there for a while, you can show me more planets!"
    mc "Of course. I'd love to take you."
    na "We kiss, and we spend the rest of the trip back planning out where we want to go next."
    na "There's so much I want to show her, and I'm sure she's excited to see it all."
    na "And I'm excited too. Excited to start this next part of my life with her."
    #fade to black
    stop music

return
