label scene_12:
    na "Well, it took a few days, but I think I have everything working now."
    na "The drive's in place, albeit with a few... extra modifications to work with my custom chassis."
    na "The rest of the parts Leona and I found were more than enough to get the rest of the ship up and running."
    mc "I think... we're ready."

    #show leona

    le "Ready for what?"
    mc "Ah, hey there."
    le "Hey."
    na "Just hearing her voice is uplifting."
    mc "I was thinking... remember last night?"
    le "About the test flight?"
    mc "Yeah. I think we have things ready to go for one today. Interested?"
    le "Do you even have to ask? Of course I am!"
    mc "Well, step aboard."

    #show BG_new_ship

    na "The ship's interior is mostly how I remember it, but we had to make room for some of the older drive tech."
    na "Kind of reminds me of the old holovids I used to watch as a kid."
    na "Humans apparently thought you could get to the moon in just a tiny, cramped capsule launched out of a cannon."
    na "Now, several ages later, it looks like I'm doing much of the same."
    na "Minus the cannon part, that is."
    ju "Welcome aboard, Raine. Are we flying today?"
    ju "We can take the new girl up too. This 'new' drive you installed is pretty old, but it's twice as powerful as the one you made yourself."
    mc "Hey!"
    ju "Just stating the facts."
    na "I'm... a little insulted, but also surprised that the drive really is that powerful."
    mc "How's everything else looking, Juneau?"
    ju "Your hodgepodge assemblage of parts is looking good!"
    mc "Really? That's what you called the ship the {b}first{/b} time I tested it on Lumin."
    ju "Hah! Wait, you actually believed me? No, I mean it this time. Despite the crash, you've done a good job getting this thing back into shape."
    ju "Good job."
    mc "Heh, thanks. But it wasn't just me."
    na "Leona finally stops moving around the cabin in time for me to indirectly mention her."
    le "Oh, I helped!"
    na "Leona here found the parts we needed to get back in business."
    ju "So I've heard. Good morning, Leona."
    le "Heya!"
    le "So, anything else we need to do?"
    ju "Nope, you can just take a seat and strap in."
    le "Awesome!"
    na "Leona eagerly sits down at the nearest chair and bounces happily, waiting for me to sit down as well."
    mc "Okay, okay, easy girl."
    na "I take a seat and get the ship ready for launch."

    #plane engine SFX

    le "So how do we get to—"

    #faster engine SFX

    le "—spaaaaaaaace!?"

    na "The new drive whirs to life and rapidly accelerates us to escape velocity."
    na "In about a minute, we're at the edge of the atmosphere, successfully in orbit around Fireside."

    ju "Okay, we're stable. You guys want to try zero gravity?"
    le "Huh?"
    mc "C'mon, let me show you!"
    na "In one smooth motion, I unbuckle myself and Leona from our seats, and we start lifting out of our chairs."
    le "Ah! I'm floating!"
    mc "That's what zero gravity does, silly."
    na "I guide her around the cabin, showing her how to move around."
    le "Wheeee!"
    mc "Hey, now you're getting it!"
    na "Her eagerness is infectious. I don't know why, but when I see her grinning like that, I'm doing the exact same thing."
    na "Why haven't I been doing that?"
    na "How long has it been since I've really enjoyed myself?"
    na "And Juneau always said that I needed a vacation. Somehow, I don't think this is what she had in mind..."

    #timeskip

    na "Sometime later, we finish up our test flight and land back on Fireside."
    le "Raine, that was amazing!"
    mc "Was that your first time flying?"
    le "Not like that. My hoverbike is the most I've ever been off the ground."
    mc "You're missing out."
    le "On Dawne, they have bigger aircraft that can take lots of people and cargo, but we don't have anything like that on Fireside."
    mc "Why?"
    le "We don't have a need for it at the moment. We've spent most of our time and resources focused on building out Aster."
    mc "Ah, makes sense."
    na "Living here on this planet is like traveling through time. All the primitive tech, the lack of familiar amenities, and the open space here is nothing like I anticipated."
    na "It's equal parts exhilarating and exhausting."
    na "I'm so far from home, and yet I'm so excited to be here."
    na "I want to head out into space, but I can't help but wonder..."
    na "Would I be happier staying here with Leona?"
    le "Raine?"
    mc "Hm?"
    le "You looked like you were spacing out again. You okay?"
    mc "Yeah, sorry. Just a bit tired."
    le "Well, it's getting late anyway. Let's head home! I'll cook for you."
    mc "I'd like that."
    na "With the ship repaired, it's a simple matter to land within a few minutes of Leona's house."
    na "Leona points at the controls, asking about all of their functions while I fly us home."
    na "She's seriously cute when she does that."
    mc "Okay, we're here!"
    le "All right! That was incredible, Raine. I'll get dinner started!"
    na "Leona wastes no time in jumping out of the ship and setting up dinner."
    na "As she leaves, Juneau materialises next to me."
    ju "You know, you need to make a decision soon."
    mc "Yea, yeah."
    mc "How was the analysis?"
    na "While Leona may have been the primary focus of our journey, Juneau and I had one other... secondary mission."
    ju "It's still there, but not for long. We have a little over a day."
    mc "Until the wormhole's gone forever."
    ju "Until the wormhole is gone forever."
    na "I nod to Juneau, understanding the gravity of the sitation. No pun intended, this time. I take my leave for the night."
    na "This very well may be the last chance I get. After today, I won't be able to see Leona's house... or her. I'll enjoy it while it lasts."
    na "As Leona continues her cooking, I can't help but think about our conversation the other night."
    na "Would Leona really be okay with me taking her with me?"
    na "She's got so much here: her people, her culture, and I'm sure she's got a lot of close friends and family she'd miss, too."
    na "And yet..."
    na "It'd be so easy to say 'yes' and take her with me."
    na "She'd be overjoyed. But is she doing this because she's in love with—"
    na "Oh my God."
    le "Raine? You there?"
    na "That's why she wants to come with."
    na "I'm such an idiot."
    mc "Ah, sorry. I'm more tired than I thought."
    le "Maybe some food will help! Come on, eat with me."
    mc "Can't say no to that. Thanks, Leona!"
    na "The food is delicious. As always, Leona's got an amazing sense for cooking."
    na "We enjoy a wonderful night in, staying close and enjoying each other's company."
    le "Hey, Raine..."
    mc "Yeah?"
    le "Tell me about Lumin."
    mc "Why?"
    le "I just want to know what your home is like."
    mc "Well, it's mostly urban. The whole planet is one big city, save for a few aforementioned places."
    mc "The entire city is this one big hub of information, electricity, and people."
    mc "For a while, it was home."
    mc "I managed to make a living as an engineer and for a while, it was fun."
    le "For a while?"
    mc "Yeah."
    mc "Something in me just got... sad, I guess. I wanted to see what was out there."
    mc "I kept thinking to myself, 'Is this it for me? Could I be doing more with my life?'"
    mc "So I decided I'd get out there and explore. I built a ship and took off."
    le "And that's how you ended up here?"
    mc "Eventually, yeah."
    le "I think I understand. You really wanted to explore, like me."
    mc "Yeah."
    le "That's so cool! I don't know if I would have been able to do all of that on my own."
    le "You're really brave."
    mc "Heh, thanks."
    mc "It was pretty scary, actually."
    mc "I just... up and left without much fanfare. Heck, my apartment is still there with a few of my things."
    mc "It was kind of impulsive."
    le "I'll say!"
    mc "But, you know..."
    na "I reach out and hold her hand."
    mc "I'd do it all over again if it meant I could meet you every time."
    le "Raine, I... wow."
    na "Her cheeks are so red they're practically glowing."
    le "That's um..."
    le "Um..."
    le "..."
    #show kiss_CG1
    #pause (3)
    na "The kiss lingers in the air, fading out all of the sounds of the city outside."
    na "The two of us say nothing for a while as Leona holds me close to her."
    #pause (3)
    le "Raine... I like you. I {i}really{/i} like you. Like, {i}like{/i} like you."
    le "I just... don't want you to go, Raine!"
    le "I don't want to be alone."
    #show kiss_CG2
    na "Her voice breaks as she starts crying."
    na "I'm stunned. All I can do is hug her tighter in response."
    na "There's so much I want to say."
    na "But I can't."
    na "Leona's been there for me, ever since I fell out of the sky."
    na "She's given me a home, showed me the beautiful planet, and even given me a reason to stay in one place for longer than a few days."
    na "But I still feel that yearning for more adventure."
    na "I know that I can't stay here."
    na "I know that I'll always want to travel amongst the stars."
    na "But still..."
    na "But still."
    mc "Leona."
    #show kiss_CG3
    na "I love you too."
    na "My body is screaming at me to say it."
    na "But I can't do it."
    mc "Forgive me... but I have to leave Fireside."
    mc "The wormhole is going to close in a few days."
    mc "I have to go now, or I'll never make it home."
    #end CG
    mc "You know it's a one-way trip."
    mc "If I — or both — of us go through there, we might not come back here for a while."
    mc "I hate to admit it, but you were right. We might not come back here ever again."
    mc "Do you think you can really leave your people here, just like that?"
    le "Didn't you?"
    mc "..."
    le "You don't think I can make those kinds of sacrifices, too? That I should just stay here and forget all about you?"
    le "No. I can't ever forget about you, Raine!"
    le "If you think you have to do this all by yourself, that's fine."
    le "But it's not fair to me."
    na "Leona continues to cry, I can no longer hold back my tears either."
    na "I know."
    mc "I need some fresh air."
    na "I run outside towards the ship."
    #show outdoors_night
    na "The night air is cool and crisp, like a slap to the face."
    na "I have to do this now, or I'll miss my chance."
    na "If I leave the way I am now, I can do it with no regrets."
    na "Finally, the ship comes into view."
    na "God, I'm such a coward."
    na "I made up my mind. I told myself that I'd take her with me. But I'm not really good with commitment, am I?"
    na "This is it. It's time to leave Fireside behind for good."
    mc "Open up, Juneau!"
    mc "We're heading out."
    na "The ship's bay doors open, and I hop inside."
    ju "It's so late, though... can't it wait until morning?"
    #show inside_ship
    mc "No, we should leave early before the wormhole closes."
    ju "And your girlfriend? Is she coming, too?"
    mc "I..."
    ju "I saw the way you looked at her earlier. You're in love with her, right?"
    mc "What makes you say that?"
    ju "The Raine I know doesn't smile like that at just anyone."
    ju "Not even me."
    ju "And frankly, I'm insulted."
    mc "About... what, exactly?"
    ju "That you fall head over heels for an alien, yet you still insist on putting your boots up on my console every time, despite all we've been through."
    ju "Honestly, you humans are so weird about love. It's like you're hard-wired to do the most ridiculous stuff when your hormones go off."
    ju "You do a lot of stupid shit, you know. I need someone else to check you, it's obvious that I can't do the job alone anymore."
    mc "I'm not... stupid."
    ju "Bullshit."
    #pause (5)
    mc "...Shit."
    na "I've never seen Juneau get so real with me."
    na "I needed that reality check, huh?"
    na "She's right, I do love Leona, and I can't just run away whenver I'm scared."
    na "For an adventurer, I'm really bad at handling the unexpected."
    mc "Juneau... thank you."
    ju "That's what I'm here for. Now go, before you make things worse."
    #show leona_house
    na "I run back to a still-sobbing Leona, who's curled up in her piles of cushions in a vain attempt to sleep."
    na "She instantly embraces me."
    le "Raine!"
    mc "I'm sorry. I was being selfish."
    mc "I was so focused on getting home I didn't stop to think what would happen if I..."
    mc "If I fell in love with you."
    le "Raine..."
    mc "But now I know what I should do. I always knew. I'm just really, really dense."
    mc "I'm taking you with me, Leona, because we need each other in this beautiful universe."
    le "You really scared me, Raine. This entire time, I was afraid that you'd just up and leave me."
    le "You almost did, too!"
    le "But... I'll go with you. Wherever you want to go."
    le "And that's because I know that no matter what, we'll have fun."
    mc "I'm really sorry. I know that doesn't really mean much now. I mean it, though."
    le "I'll forgive you, Raine, on one condition."
    le "Don't you ever, ever do that to me {b}ever{/b} again."
    mc "Y-Yeah. You're absolutely right."
    #show kiss_CG4
    na "We kiss again, but this time it's different."
    na "We're not pulling away from each other, we're getting closer and closer."
    na "I'm falling into Leona, and all the heat and pressure that comes with it feels so relieving."
    na "And I know she's feeling the same way."
    mc "I love you, Leona."
    le "I love you too."
    na "We stay in each other's arms for a long, long time after that, until we both fall asleep."

    #timeskip

    na "The next day, I help Leona pack her belongings and get the ship ready for travel."
    na "The hardware I installed makes things a bit cramped, but I think it'll work out."
    na "The first thing we're doing is upgrading this ship to be more roomy, for sure."
    ju "You sure have a lot of stuff, Leona."
    le "Can't leave home without all of these!"
    na "She motions to her bedding, her outfits, and a variety of other knick knacks she's collected."
    ju "I sure hope we can get into orbit with all of this."
    mc "Oh hush, it's fine. You know that the new engine is definitely powerful enough for that."
    mc "Besides. Think of the upgrades we can make to this baby once we hit Danhamye or any of the other colonies."
    mc "The extra I.S.O.C chips are old, but collectors will salivate for anything that ancient."
    mc "Something about 'vintage firmware' that they can use will sell well on pretty much any market."
    ju "I demand a new console, for starters."
    mc "Deal."
    na "The ship looks more and more like Leona's house than it does mine."
    na "Pretty much all of my belongings were destroyed during re-entry, so all I have left is the stuff currently on my person."
    na "Still, Leona's house had its comforts, and we thankfully were able to fit the things that mattered, plus a few extras."
    na "She's dying to show me more of her cooking sometime, so she's brought some of her cookware."
    na "I didn't have the heart to tell her that there's no stove on board, just the synthesizer."
    na "It wouldn't be that hard to install one later, though."
    na "Leona: the GOAT homemaker."
    mc "Well, I think that's everything."
    le "Got anything else you want to grab before we say goodbye?"
    mc "You packed extra o'eke'ke, right?"
    le "Yup!"
    mc "Then we're fine."
    le "Yay!"
    mc "Are {b}you{/b} ready, Leona? It's going to be a long time before we see Fireside again."
    le "I wouldn't have packed all of my life into your ship if I wasn't ready, Raine."
    na "She sits down and straps herself in."
    le "Let's go!"
    mc "All right then!"
    mc "Juneau, you know what to do."
    ju "Roger that. Starting up the engines."
    #engine startup
    na "I turn to Leona as I take the ship up."
    na "She gives me her trademark grin as she observes the scenery outside."
    na "Fireside quietly falls away as we reach orbit, the exosphere, and finally, open space."
    le "Is it going to be okay, the wormhole?"
    mc "I'm ready this time. I know where it is, and where it'll spit us out."
    mc "Juneau, you have the coordinates, right?"
    ju "Right here."
    na "The wormhole's location pops up on a nearby monitor. Not too far away."
    ju "It's definitely going to close soon. Probably within the next 24 hours."
    ju "Either you go now, or never again."
    ju "You sure you want to go?"
    na "I look to Leona."
    na "She nods, determined."
    mc "We're sure. Let's go."
    ju "All right, then. Setting engines to maximum!"
    #engine SFX
    mc "The engines accelerate us closer and closer to the wormhole's event horizon."
    ju "600 kilometers until breach."
    mc "Well, here we go, Leona."
    mc "It'll be quite a trip, don't you think? There's a lot out here."
    le "Yeah. But I'm excited to see it all with you."
    na "She leans in for a kiss."
    mc "Thanks, Leona. For everything."
    ju "300 kilometers."
    mc "You're really something out of this world, you know?"
    le "I'd say the same to you, Raine."
    na "Juneau rolls her eyes at our cliche."
    ju "Disgusting."
    na "We laugh as the ship gets closer and closer to our destination."
    ju "Fifty kilometers."
    na "This is it. I'm finally starting on my great adventure..."
    na "No."
    na "That adventure ended when I met Leona."
    ju "Ten."
    na "When I fell in love with her."
    ju "Five."
    na "And now..."
    #wormhole SFX
    ju "Entering event horizon. We're in the wormhole!"
    le "It's so pretty!"
    na "I'm starting another great adventure with Leona, one that's going to be ten times the adventure the last one was."
    na "One that I can enjoy with her to the fullest."
    mc "Hang on to your belt, the trip is a little bumpy."
    #wormhole intensifies
    na "The intensity of the wormhole momentarily spikes."
    ju "Gravity is getting stronger here. Watch out!"
    mc "Got it!"
    #switch SFX
    na "I make some on-the-fly adjustments as the ship careens into oblivion."
    na "Leona's fascinated by it all, enraptured by the lights and colors around her."
    na "God, she's cute."
    na "Soon, the gravity settles down, and Juneau senses that we're near the end."
    ju "Getting ready to decelerate. Don't want to collide with {b}another{/b} asteroid as soon as we leave."
    mc "Good call."
    mc "Almost there. And...."
    na "The ship finally exits the wormhole."
    mc "We're out!"
    ju "Decelerating."
    na "The ship slows down until we get to a more reasonable speed."
    ju "Exit confirmed. We're about a lightyear from the nearest planet, according to our maps."
    na "Now back in familiar territory, I finally sigh in relief."
    mc "Well Leona, we're here!"
    le "That was awesome! Where should we go first?"
    mc "I think we should try this place out."
    mc "I scroll my map to one place I've been thinking about for a while."
    le "What's that planet?"
    mc "Lumin."
    mc "Home."
    mc "You've shown me your home, so how about I show you mine?"
    le "I'd love that."
    mc "Juneau, take us home."
    ju "Sounds good to me."
    mc "I'm going to be honest, I wasn't entirely sure we'd make the trip back."
    le "I never doubted you. I'm glad you got us here safe and sound."
    mc "Yeah, me too,"
    le "Well, I'm ready to see your home planet."
    le "Maybe after we stay there for a while, you can show me more planets!"
    mc "Of course. I'd love to take you."
    na "We kiss, Juneau tells us to get a room, and we spend the rest of the trip back planning out where we want to go next."
    na "There's so much I want to show her, and I'm sure she's excited to see it all."
    na "And I'm excited too. Scared, but excited."
    na "We'll get you back home one day, Leona. I promise."
    #fade to black

return
