label scene_4:
    play env "amb/workshop.ogg" fadein 2.0
    na "After turning around and heading back to her street,  we reach the base that my poor ship has been taken to."
    na "I hope Juneau is okay, or that her programming is at least salvageable. She's annoying, but she's all I have."
    na "I guess she's what I imagine family to be."
    le "So, how's it look?"
    na "Leona snaps me out of my thoughts as I rest my eyes on what's left of my ship."
    mc "Oh... oh god, it's terrible!"
    le "Hey, our base is – oh, you meant your ship."
    na "I run over, pushing aside some people investigating it. They shoot me dirty looks, but upon seeing Leona, they take the hint and leave."
    le "So what's wrong with it? Not to be obtuse, but we don't exactly have ships like this on Fireside."
    mc "Well... first of all, it's upside down. It probably crashed that way, based on which parts took the most damage."
    le "Can you fix it?"
    na "I lean down to look at the roof of the ship, now planted into the ground, pieces of scrap metal poking out in several ugly shapes and directions."
    mc "Not sure. The hardware will be a pain to repair, but I can do it."
    mc "The software is the issue. If it's trashed, I'm not sure if I can fixit."
    na "Juneau... please be alright."
    le "Hey, don't look so down!"
    le "I'm sure you'll get it fixed! You're a high-tech alien, I'm sure this is nothing for you!"
    mc "Heh. While your baseless confidence is flattering, I think you might be overestimating me."
    play sound "sfx/metal fix.ogg"
    na "I push together two pieces of metal, one of which was mildly bent. Holding them in place, I readjust the screw that originally held them together."
    le "Regardless, you'll be staying with me until you've got your ship back together."
    na "I stand up, brushing myself off."
    mc "I guess I don't have much of a choice, do I? Guess I'm stuck with you."
    le "Hey, I'm a delight to live with!"
    mc "Your cooking certainly is."
    na "We both laugh, a light atmosphere growing between us."
    le "We have some tools in the storage room. There's a guy working in there that can help you find what you're looking for."
    mc "You're not coming?"
    le "I kinda wanna look at your ship. It's alien technology! I've never seen anything like it."
    mc "Sure, just don't break anything."
    na "I say it in jest, smiling at her as I walk in the direction of a door with a sign that reads 'STORAGE ROOM'."
    na "Behind me, I listen to Leona talk to herself as she prods about with my ship."
    le "..."
    le "This is really amazing stuff, even when it's in shambles."
    le "I never could have imagined this type of metal could be used like this..."
    le "...or that this shape would make for a good space ship..."
    le "...or that... or..."
    play sound "sfx/metal break.ogg"
    le "..."
    le "...oops."
    le "That was the part Raine just fixed, wasn't it?"
    le "Well, it didn't seem like she had much trouble with it, so I'm sure she can just do it again."
    le "I can't believe I managed to break the one thing she managed to repair. Not a great omen."
    na "Leona notices me as I come out of the storage room. She looks a bit panicked."
    na "I've caught her red handed."
    mc "What's wrong? Everything okay?"
    le "Yeah! Totally! Um, actually no, it's not..."
    mc "Leona?"
    le "Well, I, uh... I forgot there was a sale on eggs today, but it's gonna end soon! We should go!"
    na "I open my mouth to respond, but words escape me as she grabs my hand and pulls me along."
    le "Oh yeah, did you find any useful tools?"
    mc "I looked around, but I didn't know what any of them did. They all looked like strange toys an imaginative child might have."
    le "Was there nobody there to help you?"
    mc "Someone was working, but I don't think they could help...."
    mc "No offense, but the stuff you have here is more than a little bit out of date."
    le "Hey, we do our best! It might be for the best, though. Everyone's a little nervous about meeting an alien!"
    #VA chuckle
    mc "That's fair."
    na "After a couple of hours working on the ship, I decide to take a break. Juneau won't be online for a little bit anyways, so I have some time to kill."
    na "And I'm hungry."
    na "After a short trip to a nearby convenience store, we return to Leona's abode, eggs in tow."
    stop env fadeout 2.0
    play sound3 "amb/Leonas house.ogg"
    na "...It's already mid-afternoon."
    na "If I go back to the base to work on my ship now, I'll be there all night."
    na "Juneau..."
    le "Did you hear me? Helloooo?"
    mc "Oh! Ah, what?"
    le "I asked if you wanted dinner. Are you okay?"
    mc "Yeah, just thinking about the ship."
    le "You said you'd have trouble if the software was busted. I thought you'd know how to simply redo it."
    mc "It's not recreating the software I can't do. It's getting back the program I had."
    na "Leona sets food down in front of me. I'm not entirely sure what it's supposed to be, but it seems she used ingredients based on what she knew I could eat."
    na "As expected, it's delicious."
    le "So what's so important about the program?"
    mc "I had an AI. She was my only companion while I traveled the stars."
    na "I can't help but show pain on my face."
    le "...She must be very important to you."
    na "Leona seems upset for me, but it's almost as though she feels the sadness herself as well."
    mc "Well, we had our fights, but she was the closest I had to family."
    mc "Like an annoying little sister."
    na "Leona's long ears seem to perk up, but she covers her expression by taking another bite of food."
    mc "This sucks."
    le "Yeah..."
    le "But!"
    mc "But my world wouldn't be the same without her, so the sooner I can get her fully operational again and get back to exploring, the sooner I can get back to living my life."
    le "Are you not living your life now?"
    mc "Pardon?"
    le "Here, on Fireside. Is being here somehow putting a pause on your life?"
    le "I would think finding a species you've never seen before is exciting."
    na "She smiles sadly and looks away."
    le "I was excited to meet you."
    na "For a moment I don't know how to react."
    mc "Of course meeting you has been amazing. I never thought I would meet such a beautiful and optimistic woman here."
    na "Leona's face turns a bright red as she stares at me, speechless."
    mc "D-Don't take that the wrong way! I'm just saying that you've been the highlight of this little roadstop."
    mc "I just can't take staying in one place for too long, you know? I'll feel like I'm trapped."
    na "Leona takes my empty plate back to the counter to wash it."
    le "I guess I understand. But if I had to be trapped with someone, I wouldn't mind that being you."
    na "I don't know how to react as I twiddle my thumbs, looking anywhere but at Leona."
    le "Well!"
    na "Leona's sudden change of tone catches me off guard."
    le "You're gonna need rest if you'll be spending tomorrow fixing your ship!"
    le "I've got a change of clothes for you, and I'll set them on the bed you used yesterday."
    le "Consider that bed and those clothes yours, at least for as long as you're here."
    na "Her bright exterior seems a bit forced, but I simply smile."
    mc "Thanks, Leona. I really appreciate it. You've been amazing, I really don't deserve your help."
    na "Leona turns from me."
    le "Just doing what anyone would do. Now, make sure you get some rest! Ya need a strong and healthy mind to get her back!."
    na "I want to say something more, but I know there's nothing I can say. My thoughts return to the repair of my ship."
    na "I'm running out of time. Or I'm already out of time - I'm not sure of either. I have to assume that the wormhole won't be there forever."
    na "But there's nothing I can do until I have Juneau back, and that has to wait till tomorrow."
    na "Resigned to this fact, I follow Leona's advice and head to bed."
    stop sound3 fadeout 2.0
    jump scene_5
