label scene_3:

    #iris open
    #show bg_leonahouse

    na "I wake up to an unfamiliar place. Some kind of hut?"
    na "Oh, wait. I remember now. I crash-landed."
    na "I met an alien named Leona before immediately falling asleep."
    na "Where is she, by the way?"

    #movement SFX

    le "Hey Raine! You awake? You've been out for a long time, the sun just came up!"
    mc "Yeah, I'm kind of a heavy sleeper. How long was I out for?"
    le "About sixty ticks or so."
    mc "Sixty... hours?"
    le "I don't know what an 'hour' is, but you've been out the entire evening."
    na "Ah, it makes sense that they'd had some different units of measurement."
    na "So assuming I landed mid-afternoon, I've probably been out for sixteen hours, give or take."
    mc "I see."
    le "No problem! Want some food? I'm cooking some stuff right now if you want some!"
    na "The smell of oil and vegetables cooking in a pan is unmistakable."

    #stomach growl SFX

    na "My stomach immediately begs for something edible."
    mc "Sure, I'd like that."
    le "One plate of grub, coming up!"
    na "A few moments later, and Leona slides a dish onto the table."
    na "It's a strange collection of what appears to be purple disks, a deep orange-colored fried egg, and... white jelly?"
    mc "What's this?"
    le "Let's see... sliced inop root, some o'eke'ke, and fresh iwaiwa eggs!"
    na "Huh… those didn't translate. I don't know what these could actually be."
    na "Despite the alien nature of these, it smells really good."
    na "Food is food. If we share similar biology then this should go down without much of a fuss, right?"
    mc "Thanks for the meal, Leona."
    mc "..."
    mc "Blech!"
    mc "This inop root... it's so spicy!"
    na "I can't even chew it without an intense wave of heat burning my tongue. "
    le "Spicy? What do you mean?"
    mc "Mouth... on f-fire..."
    le "Oh no!"
    na "She grabs a glass of water and splashes my mouth — and the rest of my face — with it."
    mc "Ack! How can you eat that?!?"
    mc "My eyes are watering and my tongue feels like it's swelling up."
    le "I don't know! I don't know what you mean by 'spicy'! Inop root is just a..."
    na "Her eyes widen."
    le "Oh shoot! None of the animals here on this planet will eat this stuff! That must be it!"
    le "I didn't realize that! I'm so sorry!"
    na "Apparently she has no concept of spicy foods. Damn, her species must have one helluva tolerance for that stuff."
    na "Well, now's a better time than any to explain some of this stuff to her."
    na "...I don't want a repeat of this. Hell, who knows what food here is perfectly fine for her kind, but absolutely toxic for mine?"
    na "Better safe than sorry."

    #timeskip

    mc "So that's why it hurts to eat spicy food."
    le "Wow, that 'capsaicin' stuff must really hurt your species, then."
    le "Again, sorry about that. I should have thought about it before giving you our food."
    mc "I'm just surprised that your species isn't affected by it."
    le "Are you still hungry?"
    mc "Let me try the other food; surely that's not too bad, right?"
    le "I guess so..."
    na "She nervously looks at me as I take a bite of the o'eke'ke."
    mc "..."
    mc "Oh!"
    mc "It's good!"
    na "The o'eke'ke is almost like a custard or pudding. It's very sweet."
    le "Oh, yay!"
    mc "Now for the egg..."
    #pause 1
    na "My eyes widen. It's incredibly rich, almost like hollandaise sauce."
    na "I quickly wolf it down."
    mc "Wow, that hit the spot. What's in there?"
    le "Hm? It's just an egg."
    mc "Sorry, these eggs are... much different than the ones I'm used to."
    le "It looks like you can eat those things just fine, though. That's good!"
    mc "I was worried about that for a second."
    mc "Glad I won't be starving anytime soon."
    le "Need anything else to eat?"
    mc "I'd love another one of those eggs, actually."
    le "Coming right up!"

    #timeskip

    mc "Ahh, that was really good. Thanks for breakfast, Leona."
    le "I'm glad your fast was broken!"
    mc "No, that's... what?"
    le "You were fasting, and now it's broken, right? Is that what that word means?"
    mc "In the literal sense, I guess. But it's just our name for our morning meal."
    le "Oh, okay!"
    na "She seems to take this in pretty naturally."
    le "Well, then I'm glad I helped!"
    le "That reminds me, you're not from Dawne, but you speak Oleloahak just fine. What's up with that?"
    mc "Oh, I have an implant that automatically translates foreign languages for me. So to me, it sounds like English, but the implant does the talking for your… Oleloahak?"
    le "I see. That's some impressive technology. Your civilization must be quite advanced!"
    mc "Yeah, we made a lot of settlements after our native solar system was colonized."
    mc "A few centuries after that we finally mastered the use of faster-than-light travel and we've been expanding ever since."
    mc "Unfortunately, I didn't get here by FTL travel, though. I got here through a wormhole. Honestly, I'm pretty amazed that I survived the whole ordeal."
    na "I need to get Juneau back as soon as possible. Wormholes aren't exactly the most stable things in the universe - who knows when this one will close."
    le "Woah, wormholes? Those super-unstable gravity wells?"
    le "Yeah, you should have died."
    mc "Y-Yeah..."
    le "Ah, sorry! What I meant to say is that you're extremely lucky. None of our tests with wormholes have proved successful."
    le "I'm surprised you took a ship through one to begin with."
    mc "I didn't really have a choice. I ran into one while I was flying."
    mc "When I exited the wormhole, I was close to Fireside. My whole system shut down, so I was forced to land.."
    le "Wow, that's a lot."
    le "I'm just glad you're okay after all of that."
    le "You even went through a wormhole! I never thought that would be possible."
    mc "Yeah... I guess so."
    na "Leona suddenly stands up."
    le "So, I think it's high time I took you on a short tour of Aster!"
    na "Wow, she accepted all of that pretty quickly."
    le "If you're going to be with us, you might as well make yourself at home, right?"
    mc "Umm..."
    na "I honestly don't want to stay any longer than I have to. Leona's a wonderful host, but planetary life just isn't for me."
    mc "Maybe later."
    le "Don't you want to go outside? You can't stay cooped up in here forever..."
    mc "Once I fix my ship, I'll be fine."
    na "Leona perks up at the mention of my ship."
    le "Oh, that's right! While you were out, my crew managed to track down the ship."
    mc "R-Really?"
    le "Yeah, they've moved it to the base."
    mc "Well then, what are we waiting for?"
    le "Oh? Didn't you just say you could wait until later?"
    na "Leona's giving off the cheekiest grin. She knew I'd jump at this opportunity."
    mc "I've... changed my mind. Let's go."
    le "All right!"

    #show city_outside

    na "Leona's neighborhood is full of people just like her, with different horn shapes and a variety of builds."
    na "They're super similar to humans, minus the whole 'having horns' part."
    na "Were I more interested in xenobiology, I'd certainly be interested in how they grow. Are they part of the skull, or are they more like antlers?"
    le "And there is Xennia's place, who has the best vegetables this time of year, and over there's my mechanic's house..."
    na "Meanwhile, Leona is dragging me around, pointing at various buildings and landmarks without a care in the world."
    mc "Just how far away is this base of yours?"
    le "Oh, right across the street from my house!"
    mc "Wait, aren't we walking away from it, then?"
    le "Yep!"
    mc "..."
    le "...?"
    mc "Can I see my ship?"
    le "Oh! Right, just this way!"


    jump scene_4
