
label scene7: 
    #ART - FOREST BG (NO SHIP)
    #VFX - BG Should be super zoomed in too. See end of this scene for clarity.

    ###
    scene forest with zoomin 
    mc sighing "Lovely. I was sort of hoping I'd never see this neck of the woods again."
    mc "Why are we here again?"
    #tbh im kind of confused on whether to add leona here. i will probably figure that out loud
    le explaining "Remember the alien tech we found while bringing in your ship?"
    le "I was thinking the crash uncovered some supplies that got left behind by the previous inhabitants, but then we found all that crate inside the cave."
    le questioning a3 "Why is there stuff all the way out here when the cave base would suffice?"
    le "Think about it; a hidden base inside a cave, things buried underground-"
    mc questioning2 "Rooms full of bodies?"
    le concerned "Y-Yeah."
    mc "You might be onto something."
    le "What's more, why haven't we found anything out in the open?"
    le questioning2 "Was this place really colonized at some point if there are no other structures?"
    mc "Assume it wasn't a populated planet then."
    mc questioning "What else would someone be doing here, living in a cave and hiding stuff underground so far away?"
    le explaining "I'm pretty sure whoever was here before us was a criminal, perhaps a smuggler."
    mc "That would make some sense, but it doesn't explain why there's stuff all the way out here."
    le "That's just it, isn't it?"
    le questioning2 "We didn't find much of anything in the cave, except some old books."
    le "And it's not like we can read them anyway."
    mc satisfied "Actually, I might be able to help with that!"
    le happy a1 "You can? How?"
    mc "I can't actually speak your language, remember?"
    le happy a2 "Oooh, your translator! I didn't think about it, but that must be why you can use the mediapad I gave you."
    mc neutral "Yeah, works just as well for the written word. Gimme one of the books and I'll take a look-see."
    na "Leona quickly shuffles through the hoverbike's storage compartment, coming out with one of the dusty books we'd brought back with us."
    le concerned "Careful, it might fall apart if you're too rough with them."
    mc satisfied "If it can survive in a cave for a thousand years and then make it through your deathtrap of a bike in one piece, I doubt my delicate hands will be enough to leave a scratch."


    #SFX - PAGE TURNING



    mc speaking "Looks like nothing but random squiggles."

    #SFX - PAGE TURNING

    mc "More squiggles..."

    mc surprised "Squig- Wait! Here we go, finally kicking in!"
    mc questioning2 "Eh? Looks like a manifest of some sort."
    mc speaking "Food, water, all sorts of supplies and components like batteries and computer chips."
    mc "The whole thing is just that. Every page a different list. No names, just numbers."
    mc "Get me a different one."
    le questioning a2 "Here."
    mc questioning2 "...Nope. Just more manifests. Are they all like this?"
    na "One by one Leona brings out the other handful of books we'd brought with us."
    mc "It's just the same boring shit in all of 'em. They're useless!"
    le "But this lends credence to it being a smuggler, doesn't it?"
    mc "How do you figure that?"
    le sassyquestioning "Well, whoever these belonged to obviously didn't care about them."
    le "If they were real, they wouldn't have been left behind like that."
    le "Record keeping is an important part of trade, so leaving them there would be a really bad move for an employee and a nightmare for an employer."
    le "But if they were a smuggler, they could just cook up another set of books."
    mc unimpressed "Or they were intending to get rid of evidence of smuggling, thinking nobody would find it there."
    le questioning2 a1 "That leads me back to the stuff we found with your ship though."
    le "Why go through the trouble of building something so deep inside a cave, hiding evidence of smuggling there but not leaving the smuggled cargo with it?"
    mc "I think you're onto something. It doesn't quite make sense, does it?"
    mc "Come to think of it, we found the cave because the power source inside shows up on sensors."
    mc "You might as well leave a giant arrow pointing straight to it."
    le questioning2 a3 "...Huh. That's a really good point."
    mc surprised "What if it's not a decoy, but a trap?"
    le surprised "A trap? Why would-"
    mc questioning2 "Leona, what about the bodies you found?"
    mc "A room full of corpses halfway through the cave. At the back of the cave there's a sealed room and a crate full of cargo manifests just sitting there for anyone to find."
    mc surprised "That entire cave had to have been a trap. Whoever those people were must have been killed before they could find these manifests!"
    le speakingsurprised a1 "W-Well, I don't know about-"
    mc neutral "We found them though!"
    mc "But then we couldn't get the door open right away, so we decided to come back with something to power the control panel."
    le "No, I-"
    le "Wait. What are you getting at?"
    mc questioning2 "What if the door is a trap set for whoever wanted to find the smuggled cargo?"
    mc "Let's consider that there isn't actually anything inside. The cargo they were looking for was actually all the way out here, buried in the middle of a forest."
    mc neutral "Think about it. A beacon to draw people in, trapped doors to kill off intruders and at the very back of the cave there's a pressurized room."
    mc questioning "Leona, what if it's a bomb?"
    le concerned "A bomb? I don't understand, how can a room be a bomb?"
    mc "I don't know. Maybe there's something inside set to go off as soon as..."
    mc "...as soon as..."
    mc questioning2 "...the pressure is released when the door opens."
    le questiong a3 "Raine, didn't that hole start making a whistling noise when you pulled that bolt out?"
    mc unimpressed "Crap."
    le speakingsurprised a1 "What do we do?!"
    mc "Absolutely nothing."
    le  surprised "What? No! A bomb is gonna go off!"
    mc yawning "Relax, it can't be that strong."
    mc "Why set up traps to kill people before they can even get to the door, if opening it is just going to kill everyone anyway?"
    le sad "...Uh, R-Raine?"
    mc neutral "Yeah?"
    le "I have a bit of confession and you're not going to like it."
    mc questioning "Go on...?"
    le "Promise me you won't be mad?"
    mc annoyed "...That depends, Leona. What are you confessing to?"
    le "That room? With the bodies?"
    le "It uh... It didn't actually, sort of, have... any?"
    na "..."
    mc unimpressed "What?"
    le "I miiight have l-lied..."
    mc upset "Why would you- Wait, what was glowing then?"
    le speakingsurprised "There was a room, but it didn't have any corpses inside."
    mc annoyed "Leona, what did you see?"
    le "It was this big, green glowy canister like thing sitting in the middle of the room with a bunch of wires coming out of it."
    mc "That could have been the power source we were looking for."
    mc unimpressed "But why would you...?"
    mc "Waaait a second. If there aren't any traps before the door at the back-"
    mc questioning "That means the bomb might not be as small as I thought."
    le concerned "How big do you think it could be?"
    mc unimpressed "I don't know. Big enough to blow away the entire cave, I imagine."
    le "Or anyone foolish enough to get close to it, looking for the smuggled cargo."
    le "Raine, those mountains have {i}tons{/i} of cave systems."
    le speakingsurprised "A big enough explosion could cause them all to collapse at once!"
    mc upset "Get on the horn, warn everyone to get away from those mountains!"

    #SFX - Faint explosion


    na "Leona and I look to the horizon as we feel the ground shake beneath our feet, a burst of sound echoing through the air."
    na "And in the distance, visible through the treetops…"
    na "Was a large chunk of a mountain torn right from the earth."
    mc shocked armraised "Oh my god."
    na "Leona stands there, stunned in place with a terrified look."
    mc "Leona, the radio! Quick!"
    na "A gust of wind barrels through the forest, thrusting into my face as it batters the trees in its wake."
    mc "Aah!"
    na "By the time the wind dies down, Leona rushes to the radio on her bike, sweat dripping from her face."
    le explaining "This is Captain Leona broadcasting on all emergency channels!"
    le "I need reports from all units detailing locations and status on frequency 88.9, prioritizing vicinity to Southwest Mountain range!"
    na "One by one the reports roll in."
    na "Minor injuries, a number of scrapes and bruises."
    na "A single man knocked unconscious. Fortunately, everyone is still alive."
    na "Those closest to the explosion said it sounded like a storm was coming in before they saw rocks flying everywhere."
    na "The mountain just sort of caved in on itself, followed by a huge amount of smoke."
    na "Beyond that and what will eventually be a better view of the horizon, Aster only had minor damage from the shockwave."
    le "I need people out there keeping an eye on it. I'll be making a stop in Aster then I'll be out to assess the situation."
    le "All other units report to base and await our return. Captain Leona signing off."
    na "Leona stands there a moment, staring into the radio."
    mc neutral "Can we talk about this?"
    le "Um…"
    na "She opens her mouth to speak."
    na "But then turns her face away from me."
    na "..."
    mc "If you're not going to talk, then listen."
    mc "Everyone makes mistakes. There isn't a person in the universe who goes through life flawlessly."
    le sad "...I'm sorry."
    mc upset "But you lied to me. I trusted you, and you lied to me."
    le "...I'm sorry…"
    mc unimpressed "I want to know why."
    na "Head still hung low, she turned her head to me, unable to look me in the eye."
    mc "Why?"
    le sad "I-I was afraid."
    le "I only wanted to keep you safe."
    le "The room I found... I saw the power sources and got scared."
    le "For a moment I saw you back up in that tree."
    le "I thought about you being sucked into a wormhole and crashing into a planet."
    le "Not this one though. Not Fireside."
    le "Some random, lifeless rock somewhere a million miles away from any another person."
    le crying "I didn't..."
    na "She takes a step back into the bike, setting herself down on the seat."
    le "I don't want you to get hurt again."
    mc "Is that so?"
    mc annoyed "And the easiest way to do that is to keep me from leaving."
    le "I'm sorry! I was scared!"
    mc "That isn't your choice to make."
    le "But-"
    mc upset "That isn't your fucking choice to make!"
    mc "It's my life! I'm the one who decides what to do with it!"
    mc "If I wanted to spend my life huddled up in the corner of my room on some backwater planet I wouldn't be in fucking space to begin with!"
    mc "And I don't need your help if I can't trust you to understand that."
    mc unimpressed "Get the rocks."
    le speakingsurprised "R-Raine, what are you-"
    le "The ones I told you to hold on to. Right now."
    na "Looking more than a little sheepish, Leona fishes the rocks out of her bag."
    na "They're decently sized, a handful even. Much bigger than the pebbles around here."
    na "I grab one out of her hand, then point towards a big tree in the distance."
    mc "I want you to hit it."
    le "Hit? Like, go up and-?"
    mc "No, I mean throw it. As hard as you can. Hit that tree."
    le sad "I-I don't think I can-"
    mc annoyed"I don't care. Throw the rock."
    na "Still looking nervous, she reels back and lets it fly."
    na "The rock sails through the air, but barely makes it halfway to the tree."
    le "R-Raine, what is this about?"
    na "I don't give her an answer. I simply take aim and fire."


    #SFX - Rock hitting wood

    na "It sails straight like a bullet, and the bark explodes at the center of impact.."
    le speakingsurprised "Oh my god-!"
    le "What was that?!"
    mc satisfied "I could do that the whole time. I didn't figure it out until earlier today."
    mc "The gravity here is weaker than what my species is used to, so my body can handle more punishment than yours."
    mc "Stronger too, since my muscles are more dense."
    mc unimpressed "That reminds me. I have a gift for you."
    na "From my own bag I fetch the neatly wrapped box I'd prepared the night before as Leona slept."
    mc "Your present. As promised; A little \"thanks\" for all the help."

    mc neutral "It's a music player. Brought it with me from Lumin. You just hit the button in the middle when you want to start it."
    mc "I had Juneau translate the interface and attach lyrics to all the songs."
    le sad "Raine..."
    mc unimpressed "But, as you know, I won't be needing any more help from now on."
    mc "I'll see you around, Leona."
    na "I turn away from her and start walking."


    #VFX - BG and Leona sprite zooms out a step with every following line until end of scene.
    #
    ###

    le "Raine?"
    na "Just walking."
    le sad "R-Raine...?"
    na "Back to my ship."
    le crying "{b}Raine{/b}?!"
    na "Back to Aster."
    le crying2 "{b}Raaaine{/b}!"
    na "Back to a prison."
    hide le crying2 with dissolve


    #VFX - Quickly cut to black
    #Timing - add an extra couple seconds of nothing but black before next line
    #VFX - Journal entry added - 4


