Scene 4

###
ART - GARAGE BG
###
na "After heading back towards Leona's house, we turn the corner and reach the base my poor ship had been taken to."
na "I hope Juneau is okay. She's annoying, but she's all I have now."
na "She's what I imagine a little sister would be like."
le "So, how's it look?"
na "Leona snaps me out of my thoughts as I rest my eyes on what's left of my ship."
mc "Oh man, what a stinking mess!"
na "I run over, pushing aside some people investigating it. They shoot me dirty looks, but upon seeing Leona, they take the hint and leave."
le "So what's wrong with it? As I said when we met, we don't exactly have ships like yours."
mc "Well... first of all, it's upside down. It's going to be a pain to flip over."
le "But can you fix it?"
na "I lean down to look at the roof of the ship, now planted into the ground, pieces of scrap metal poking out in several ugly shapes and directions."
mc "Not sure. The hardware will be a real bitch to repair, but I can do it."
mc "The software is the issue. If it's trashed, I'm not sure if it can be fixed."
na "Juneau... please be alright."
le "Hey, don't look so down!"
le "I'm sure you'll get it fixed! You're a high-tech alien, I'm sure this is nothing for you!"
mc "Heh. While your baseless confidence is flattering, I think you might be overestimating me."
na "I push together two pieces of metal, one of which was mildly bent. Holding them in place, I grab a nearby tool and try to turn the screw that originally held them together."
le "Regardless, you'll be staying with me until you've got your ship back together."
na "I stand up, brushing myself off."
mc "I guess I don't have much of a choice, do I? Guess I'm stuck with you."
le "Excuse you, I'm a delight to live with!"
mc "And a wonderful chef."
le "Aww, that's not fair at all."
mc "Nah, I'm serious. The egg was great."
le "I can pick some more up, if you'd like."
mc "Yeeesss."
le "We'll make a stop at the store later then."
le "Anywho, there are more tools in the storage room. There's a guy working in there that can help you find something useful."
le "Well, I hope he can at least."
mc "You're not coming?"
le "I kinda wanna look at your ship. It's alien technology! I've never seen anything like it."
mc "Sure, just don't go pressing any random buttons."
na "I smile at her as I turn towards the direction of a door with a sign that reads "STORAGE ROOM"."
na "Behind me, I listen to Leona talk to herself as she prods about with my ship."
na "..."
le "This is really amazing stuff, even when it's in shambles."
le "I never could have imagined this type of metal could be used like this..."
le "...or that this shape would make for a good space ship..."
le "...or that, or..."
na "..."

###
SFX - METALLIC POP
###

le "...oops."
le "And she just fixed that too..."
le "Not a great start."
na "Leona notices me watching from the doorway."
na "I've caught her red handed."
mc "Everything okay?"
le "Yeah! Totally! Um, actually no, it's not..."
mc "Leona?"
le "Well, I, uh..."
le "...Maybe I shouldn't try to help. I'm all thumbs."
mc "No use fussing over it. It was gonna do that anyway."
le "Did you find anything useful back there?"
mc "I looked around, but I didn't know what any of them did. They all looked like strange toys."
le "Was there nobody there to help you?"
mc "Someone was working, but I don't think they could help...."
mc "No offense, but the stuff you have here is more than a little bit out of date."
le "Hmmm, I suppose it might be for the best."
le "Everyone's a little nervous about having you here. It's not every day an alien crash-lands in your backyard."
mc "Haha, I'll bet."
mc "As soon as everyone realized who I was, they cleared out of there right quick."
mc "I bet the one in the storage room is only still there because he feels a bit trapped."
le "We do some of our best work when we feel like that though."
le "Did I tell you why we decided to found a colony to begin with?"
mc "No, but I'd love to hear more."
le "Tell you what, you tell me what kind of tools you need and I'll get them for ya."
le "And while you work, I'll give you a rundown!"
mc "You've got a deal."

###
VFX - FADE TO BLACK
###

na "..."
na "After a couple of hours listening to Leona's stories while working on the ship, I decide to take a break. Juneau won't be online for a little bit anyways, so I have some time to kill."
na "And I'm hungry."

###
ART - LEONA'S HOUSE
###

na "After a short trip to a nearby convenience store in search of eggs, we return to Leona's abode."
na "It's already mid-afternoon."
na "If I go back to the base to work on my ship now, I'll be there all night."
na "Juneau..."
le "Did you hear me? Helloooo?"
mc "Oh! Ah, what?"
le "I asked if you wanted dinner. Are you okay?"
mc "Yeah, just thinking about the ship."
le "You said you'd have trouble if the software was busted. I thought you'd know how to simply redo it."
mc "It's not recreating the software I can't do. It's getting back the programs I had."
na "Leona sets food down in front of me. I'm not entirely sure what it's supposed to be, but it seems she used ingredients based on what she knew I could eat."
na "As expected, it's delicious."
le "So what's so important about the program?"
mc "She's an AI companion. She's way more than just a program."
mc "As far as I'm concerned she's a real person."
na "I can't help but show pain on my face."
le "...She must be very important to you."
na "Leona seems upset for me. Perhaps she feels the sadness herself as well."
mc "Well, we had our fights, but she's the closest I have to family."
mc "Like an annoying little sister."
na "Leona's long ears seem to perk up, but she covers her expression by taking another bite of food."
mc "This sucks."
le "Yeah..."
le "But!"
na "Leona's sudden change of tone catches me off guard."
le "You're gonna need rest if you'll be spending tomorrow fixing your ship!"
le "I've got a change of clothes for you! I put them on the bed you used yesterday."
le "Consider that bed and those clothes yours, at least for as long as you're here."
na "Her bright exterior seems a bit forced, but I simply smile. Her honest, blatant empathy is… refreshing."
mc "Thanks, Leona. I really appreciate it. You've been amazing, I really don't deserve your help."
na "Leona turns from me."
le "Just doing what anyone would do. Now, make sure you get some rest! Ya need a strong and healthy mind to get her back!"
na "I want to say something more, but I know there's nothing I can say. My thoughts return to the repair of my ship."
na "But there's nothing I can do until I have Juneau back, and that has to wait till tomorrow."
na "The wormhole that brought me here is more likely than not long gone."
na "Would it really be so bad to slow my pace here?"
na "Resigned to the facts, I follow Leona's advice and head to bed."
na "As I lay in bed, I remember the stories Leona told me earlier."
na "If I'm going to be here for a while, I guess it wouldn't hurt to document some things."
mc "Hey, Leona?"
na "Leona, who is now cleaning up after our meal, pokes her head out from the kitchen."
le "Yes?"
mc "Do you have anything I can write on?"
le "Is digital alright?"
mc "That would be wonderful."
le "Check the shelf on the back wall. There are a bunch of mediapads I bought a while ago for next to nothing, so you can keep one if you want."
mc "Whoa, thanks!"
mc "I'd feel a little guilty taking something else from you for nothing in return, so I'll make you a trade."
mc "How does a copy of my music collection sound?"
le "Alien music? That sounds exciting!"
mc "I thought that might interest you. I'll get you hooked up tomorrow."
le "You know how to drive a hard bargain!"
le "Oh, and I'm done with dishes here but I need to go check on something at the base. I'll be back in a little while."
le "Will you be okay on your own for a bit?"
mc "Sure, I just want to write some things down before I go to sleep. See you in the morning?"
le "Alrighty, g'night Raine."
mc "Night night~"
na "Leona takes her leave and I set about making notes of what I've seen and heard so far."
na "When we were talking in the garage earlier she told me an interesting story about their homeworld; Dawne."
na "I figure that's as good a place as any to start before I decide to nod off."

###
VFX - JOURNAL ENTRY ADDED - 1
###
